services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./variables.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=user --dbname=transcoder_pipeline"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    image: app
    build: ./app/
    env_file:
      - ./variables.env
    depends_on:
      db:
        condition: service_healthy # Wait for database to be healthy before starting app
    volumes:
      - files:/transcode_pipeline_app/files
      - type: bind
        source: ./app/files
        target: /transcode_pipeline_app/files
      - type: bind
        source: ./app/src/
        target: /transcode_pipeline_app/src

volumes:
  files: