services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./variables.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=user --dbname=transcoder_pipeline"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    image: app
    build: ./app/
    env_file:
      - ./variables.env
    depends_on:
      db:
        condition: service_healthy # Wait for database to be healthy before starting app
    volumes:
      - ./app/src/:/app/src/ # TODO MSA: for dev purposes only, remove before final submission
      - ./upload/:/app/upload/ # TODO MSA: for dev purposes only, remove before final submission
      - ./completed/:/app/completed/ # TODO MSA: for dev purposes only, remove before final submission